export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const SET_IS_DATA_READY = 'SET_IS_DATA_READY'
export const SET_DATA_LOADING_ERROR = 'SET_DATA_LOADING_ERROR'

export const UPDATE_NUMBER_OF_AJAX_CALLS = 'UPDATE_NUMBER_OF_AJAX_CALLS'
